from pathlib import Path
from unittest.mock import Mock

import pytest

from exercise_library.cli.editor import _edit_in_editor, _remove_generated_comments


def test_remove_generated_comments() -> None:
    content = (
        "<!--\n[myapp]:\n"
        "This is generated content.\n"
        "It spans multiple lines.\n"
        "-->\n"
        "User content.\n"
    )

    assert _remove_generated_comments(content, "myapp") == "User content.\n"

    content = (
        "<!-- [myapp]:\n"
        "This is generated content.\n"
        "It spans multiple lines.\n"
        "-->\n"
        "User content.\n"
    )

    assert _remove_generated_comments(content, "myapp") == "User content.\n"

    content = (
        "<!-- [myapp]\n"
        "This is generated content.\n"
        "It spans multiple lines.\n"
        "-->\n"
        "User content.\n"
    )

    assert _remove_generated_comments(content, "myapp") == "User content.\n"


def test_remove_multiple_generated_comments() -> None:
    content = (
        "Before.\n"
        "\n"
        "<!-- [myapp]:\n"
        "First generated comment.\n"
        "-->\n"
        "\n"
        "Keep this.\n"
        "\n"
        "<!-- [myapp]:\n"
        "Second generated comment.\n"
        "More generated content.\n"
        "-->\n"
        "\n"
        "After.\n"
    )

    assert (
        _remove_generated_comments(content, "myapp")
        == "Before.\n\nKeep this.\n\nAfter.\n"
    )


def test_preserve_comments_for_different_app() -> None:
    content = (
        "<!-- [otherapp]:\nGenerated by another application.\n-->\nUser content.\n"
    )

    assert _remove_generated_comments(content, "myapp") == content


def test_preserve_regular_comments() -> None:
    content = (
        "<!-- Regular comment -->\n"
        "User content.\n"
        "<!-- [myapp]:\n"
        "Generated comment.\n"
        "-->\n"
    )

    assert _remove_generated_comments(content, "myapp") == (
        "<!-- Regular comment -->\nUser content.\n"
    )


def test_remove_generated_comment_without_newline() -> None:
    content = "Before<!-- [myapp]:generated content-->After"

    assert _remove_generated_comments(content, "myapp") == "BeforeAfter"


def test_no_generated_comments() -> None:
    content = "Some user content.\n<!-- Regular comment -->\nMore user content.\n"

    assert _remove_generated_comments(content, "myapp") == content


def test_escape_special_characters_in_app_name() -> None:
    content = "<!-- [my.app]:\nGenerated content.\n-->\nUser content.\n"

    assert _remove_generated_comments(content, "my.app") == "User content.\n"


def test_edit_in_editor_uses_visual_over_editor(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("VISUAL", "visual-editor")
    monkeypatch.setenv("EDITOR", "other-editor")

    fake_launch_editor = Mock()

    _edit_in_editor("prompt", fake_launch_editor)

    command = fake_launch_editor.call_args[0]

    assert command[0] == "visual-editor"


def test_edit_in_editor_returns_none_if_neither_visual_nor_editor_set(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.delenv("VISUAL", raising=False)
    monkeypatch.delenv("EDITOR", raising=False)

    fake_launch_editor = Mock()

    assert _edit_in_editor("prompt", fake_launch_editor) is None


def test_edit_in_editor_falls_back_to_editor(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.delenv("VISUAL", raising=False)
    monkeypatch.setenv("EDITOR", "my-editor")

    fake_launch_editor = Mock()
    _edit_in_editor("prompt", fake_launch_editor)

    command = fake_launch_editor.call_args[0]

    assert command[0] == "my-editor"


def test_edit_in_editor_supports_editor_arguments(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.delenv("VISUAL", raising=False)
    monkeypatch.setenv("EDITOR", "my-editor --wait --foo")

    fake_launch_editor = Mock()

    _edit_in_editor("prompt", fake_launch_editor)

    command = fake_launch_editor.call_args[0]

    assert command[0].split(" ") == [
        "my-editor",
        "--wait",
        "--foo",
    ]


def test_edit_in_editor_removes_generated_comments(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("EDITOR", "editor")

    def fake_launch_editor(editor: str, file_path: Path | str) -> bool:
        with open(file_path, mode="a", encoding="utf-8") as f:
            f.write("# My exercise\n\n")
            f.write("This is **Markdown**.\n")
        return True

    result = _edit_in_editor("prompt", fake_launch_editor)

    assert result is not None

    assert result == "# My exercise\n\nThis is **Markdown**."


def test_edit_in_editor_with_context_removes_generated_comments(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("EDITOR", "editor")

    def fake_launch_editor(editor: str, file_path: Path | str) -> bool:
        with open(file_path, mode="a", encoding="utf-8") as f:
            f.write("# My exercise\n\n")
            f.write("This is **Markdown**.\n")
        return True

    result = _edit_in_editor(
        "prompt",
        fake_launch_editor,
        test_context=(
            "This is previous context\nThis should be not part of the result\n"
            + "because this is part of the generated comments.\n"
        ),
    )

    assert result is not None

    assert result == "# My exercise\n\nThis is **Markdown**."


def test_edit_in_editor_preserves_other_html_comments(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("EDITOR", "editor")

    def fake_launch_editor(editor: str, file_path: Path | str) -> bool:
        with open(file_path, mode="a", encoding="utf-8") as f:
            f.write("<!-- Keep this comment -->\n")
            f.write("Some content")
        return True

    result = _edit_in_editor("prompt", fake_launch_editor)

    assert result == "<!-- Keep this comment -->\nSome content"


def test_edit_in_editor_preserves_internal_whitespace(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("EDITOR", "editor")

    def fake_launch_editor(editor: str, file_path: Path | str) -> bool:
        with open(file_path, mode="a", encoding="utf-8") as f:
            f.write(
                "\n\n  Some content\n    with indentation\n\n  Another paragraph\n\n\n"
            )
        return True

    result = _edit_in_editor("prompt", fake_launch_editor)

    assert result == ("Some content\n    with indentation\n\n  Another paragraph")


def test_edit_in_editor_strips_surrounding_whitespace(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("EDITOR", "editor")

    def fake_launch_editor(editor: str, file_path: Path | str) -> bool:
        with open(file_path, mode="a", encoding="utf-8") as f:
            f.write(
                "\n\n"
                "  Some content  \n"
                "    with indentation    \n"
                "\n"
                "  Another paragraph  \n"
                "\n\n"
            )
        return True

    result = _edit_in_editor("prompt", fake_launch_editor)

    assert result == ("Some content  \n    with indentation    \n\n  Another paragraph")


def test_edit_in_editor_raises_when_editor_fails(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("EDITOR", "editor")

    def fake_launch_editor(editor: str, file_path: Path | str) -> bool:
        return False

    with pytest.raises(RuntimeError, match="Editor exited unsuccessfully"):
        _edit_in_editor("prompt", fake_launch_editor)


def test_edit_in_editor_removes_temp_file_when_editor_fails(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("EDITOR", "editor")

    file_path: Path | None = None

    def fake_launch_editor(editor: str, path: Path | str) -> bool:
        nonlocal file_path
        file_path = Path(path)
        return False

    with pytest.raises(RuntimeError, match="Editor exited unsuccessfully"):
        _edit_in_editor("prompt", fake_launch_editor)

    assert file_path is not None
    assert not file_path.exists()


def test_edit_in_editor_removes_temp_file_on_success(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("EDITOR", "editor")

    file_path: Path | None = None

    def fake_launch_editor(editor: str, path: Path | str) -> bool:
        nonlocal file_path
        file_path = Path(path)
        return True

    _edit_in_editor("prompt", fake_launch_editor)

    assert file_path is not None
    assert not file_path.exists()
