import os
import re
import shlex
import subprocess
import tempfile
from collections.abc import Callable
from pathlib import Path

from prompt_toolkit import prompt as tk_prompt

from exercise_library.config import APP_NAME


def _remove_generated_comments(content: str, app_name: str) -> str:
    """Remove comments generated by the application."""
    pattern = rf"<!--\s*\[{re.escape(app_name)}\].*?-->\s*"
    return re.sub(pattern, "", content, flags=re.DOTALL)


def _launch_editor(editor: str, file_path: Path | str) -> bool:
    try:
        subprocess.run(shlex.split(editor) + [file_path], check=True)
        return True
    except subprocess.CalledProcessError:
        return False


def _edit_in_env_editor(
    field_name: str,
    launch_editor: Callable[[str, Path | str], bool],
    initial_field_value: str | None = None,
    **context: str,
) -> str | None:
    """
    Return None if neither $VISUAL nor $EDITOR environment variable is set.
    """
    editor = os.environ.get("VISUAL") or os.environ.get("EDITOR")
    if not editor:
        return None

    formatted_context = [
        f"{context_field_name.upper()}:\n{value}"
        for context_field_name, value in context.items()
    ]

    prefix = f"<!-- [{APP_NAME}] "
    first_instruction_line = prefix + "-" * (78 - len(prefix)) + "\n"

    initial_edit_context = (
        first_instruction_line
        + f"(Comments starting with '[{APP_NAME}]' will be automatically removed)\n\n"
        f"{'\n\n'.join(formatted_context)}\n\n"
        + f"Enter {field_name.upper()}:\n"
        + "-" * 75
        + "-->\n"
    )

    if initial_field_value:
        initial_content = initial_edit_context + initial_field_value
    else:
        initial_content = initial_edit_context

    with tempfile.NamedTemporaryFile(
        mode="w+",
        suffix=".md",
        delete=False,
        encoding="utf-8",
    ) as tf:
        tf.write(initial_content)
        tf_name = tf.name

    try:
        editor_exited_successfully = launch_editor(editor, tf_name)

        if not editor_exited_successfully:
            raise RuntimeError("Editor exited unsuccessfully")

        with open(tf_name, encoding="utf-8") as tf:
            content = tf.read()

            if content.strip() == initial_edit_context.strip():
                return ""

            return _remove_generated_comments(content, APP_NAME).strip()

    finally:
        if os.path.exists(tf_name):
            os.unlink(tf_name)


def edit_in_env_editor(
    field_name: str, context: dict[str, str], initial_field_value: str | None = None
) -> str | None:
    return _edit_in_env_editor(
        field_name=field_name,
        launch_editor=_launch_editor,
        initial_field_value=initial_field_value,
        **context,
    )


def inline_prompt(msg: str, initial_value: str | None = None) -> str | None:
    answer = (
        tk_prompt(
            msg,
            default=initial_value,
        )
        if initial_value
        else tk_prompt(msg)
    )

    return answer.strip() if answer.strip() != "" else None
